[package]
name = "raspi-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
getrandom = "0.3.3"
rand_xoshiro = "0.6.0"
time = { version = "0.3.9", features = ["parsing", "formatting"] }
time-tz = "2"
